In [1]:
from Model import *

In [2]:
ds = DataSet()
X, y, classes, labels, idx, labels_r, X_train, y_train, X_test, y_test = ds.load_data()
print(labels)
print(labels_r)
print(idx)
print(len(X_train), len(X_test), len(y_train), len(y_test))

In [3]:
model = CNN(idx_of_classes=idx).to(DEVICE)
criterion = MSELoss()
optimizer = Adam(model.parameters(), lr=0.001)

In [4]:
hp = Help_Funcs()
(
    PROJECT_NAME,
    name,
    epochs,
    X_train,
    y_train,
    X_test,
    y_test,
    batch_size,
    device,
    model,
    criterion,
    optimizer,
) = hp.train(
    PROJECT_NAME,
    "BaseLine CNN",
    125,
    X_train.view(-1, 1, 28, 28).to(DEVICE),
    y_train.to(DEVICE),
    X_test.view(-1, 1, 28, 28),
    y_test.to(DEVICE),
    BATCH_SIZE,
    DEVICE,
    model,
    criterion,
    optimizer,
    labels_r,
)

In [5]:
img = cv2.imread('./Model/tests/download (1).jpeg')

In [6]:
img

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]]], dtype=uint8)

In [7]:
img = img / 255.0

In [8]:
img = cv2.imread('./Model/tests/download (1).jpeg')

In [9]:
img = cv2.resize(img,(28,28))

In [10]:
img = img / 255.0

In [11]:
plt.imshow(img)

In [12]:
img = cv2.imread('./Model/tests/download (1).jpeg')

In [13]:
img = cv2.resize(img,(28,28))

In [14]:
plt.imshow(img)

In [15]:
img = img / 255.0

In [16]:
plt.imshow(img)

In [17]:
img = cv2.imread('./Model/tests/download (1).jpeg')

In [18]:
img = cv2.resize(img,(28,28))

In [19]:
img = img / 255.0

In [20]:
model(img)

In [21]:
img = torch.tensor(img).view(-1,1,28,28).float().to('cuda')

In [22]:
pred = model(img)

In [23]:
pred

tensor([[ 2.9197e-03,  7.4902e-03,  5.5518e-03, -7.5343e-03,  3.9194e-03,
          3.6529e-03,  3.6635e-03,  9.8860e-01, -1.9894e-03, -2.3957e-03],
        [-1.0065e-02,  1.9817e-02,  1.3115e-01,  1.2456e-01,  8.6046e-04,
          1.2885e-03,  5.3263e-02,  5.2834e-02,  3.2557e-01,  2.6553e-01],
        [-6.3463e-03,  9.9920e-01,  1.4200e-02, -8.3139e-03, -3.0876e-03,
         -7.5566e-04, -4.9660e-04,  2.9162e-03,  1.4515e-03, -1.0431e-03]],
       device='cuda:0', grad_fn=<AddmmBackward0>)

In [24]:
model.eval()

CNN(
  (max_pool2d): MaxPool2d(kernel_size=(2, 2), stride=(2, 2), padding=0, dilation=1, ceil_mode=False)
  (activation): ReLU()
  (conv1): Conv2d(1, 16, kernel_size=(3, 3), stride=(1, 1))
  (conv2batchnorm): BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (conv3): Conv2d(16, 32, kernel_size=(3, 3), stride=(1, 1))
  (conv4batchnorm): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (conv5): Conv2d(32, 64, kernel_size=(1, 1), stride=(1, 1))
  (linear1): Linear(in_features=64, out_features=128, bias=True)
  (linear2batchnorm): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (linear3): Linear(in_features=128, out_features=256, bias=True)
  (linear4batchnorm): Linear(in_features=256, out_features=512, bias=True)
  (linear5): Linear(in_features=512, out_features=256, bias=True)
  (output): Linear(in_features=256, out_features=10, bias=True)
)

In [25]:
pred = model(img)

In [26]:
pred

tensor([[-0.0104,  0.4221, -0.0163,  0.0778, -0.0661,  0.2910, -0.0523,  0.1256,
          0.1089,  0.1288],
        [ 0.0947,  0.0569,  0.1751,  0.0548,  0.0689,  0.1180,  0.1196, -0.0694,
          0.3473,  0.0459],
        [ 0.5916,  0.0597,  0.1110,  0.0378,  0.0410,  0.1303, -0.0105, -0.0177,
          0.0180,  0.0913]], device='cuda:0', grad_fn=<AddmmBackward0>)

In [27]:
from Model import *

In [28]:
ds = DataSet()
X, y, classes, labels, idx, labels_r, X_train, y_train, X_test, y_test = ds.load_data()
print(labels)
print(labels_r)
print(idx)
print(len(X_train), len(X_test), len(y_train), len(y_test))

In [29]:
model = CNN(idx_of_classes=idx).to(DEVICE)
criterion = MSELoss()
optimizer = Adam(model.parameters(), lr=0.001)

In [30]:
hp = Help_Funcs()
(
    PROJECT_NAME,
    name,
    epochs,
    X_train,
    y_train,
    X_test,
    y_test,
    batch_size,
    device,
    model,
    criterion,
    optimizer,
) = hp.train(
    PROJECT_NAME,
    "BaseLine CNN",
    125,
    X_train.view(-1, 1, 28, 28).to(DEVICE),
    y_train.to(DEVICE),
    X_test.view(-1, 1, 28, 28),
    y_test.to(DEVICE),
    BATCH_SIZE,
    DEVICE,
    model,
    criterion,
    optimizer,
    labels_r,
)